deildu:
  login_required: true
  username: 'arivarton'
  password: '***REMOVED***'
  login_path: 'takelogin.php'
  page_path: '&page='
  search_path: 'browse.php?search='
  url: 'https://deildu.net'
thepiratebay:
  login_required: false
  page_path: '/'
  search_path: 'search/'
  url: 'https://thepiratebay.org'
